# [user]
# name = ""
# email = ""

[ui]
editor = "nvim"
default-command = "log"

[merge-tools.diffview]
conflict-marker-style = "git"
edit-args = ["-c", "DiffEditor $left $right $output"]
# edit-args = ["-c", "DiffviewDiffDirs $left $right"]
merge-args = ["-c", "DiffviewMergeFiles $output $base $left $right"]
merge-tool-edits-conflict-markers = true
program = "nvim"

[merge-tools.diffconflicts]
conflict-marker-style = "git"
edit-args = ["-c", "DiffEditor $left $right $output"]
merge-args = ["-c", "JJDiffConflicts", "$output"]
merge-tool-edits-conflict-markers = true
program = "nvim"

# [signing]
# behavior = "own"
# backend = "gpg"
