unbind r
bind r source-file ~/.config/tmux/tmux.conf

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# set -g status-right-length 150
# set -g status-right '#[align=absolute-centre]#(cd #{pane_current_path}; jj log -r @ --no-graph -T "bookmarks.join(\", \")")#[align=right]'

# set -g status-right-length 150
# set -g status-right '#[align=absolute-centre]#(cd #{pane_current_path} 2>/dev/null && jj log -r @ --no-graph -T "bookmarks.join(\", \")" 2>/dev/null)#[align=right]#(date +"%I:%M %p")'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'nyyakko/tmux-open-nvim'
set -g @plugin 'Morantron/tmux-fingers'

# set -g @ton-open-strategy ":tabnew"

# Overrides matching file paths with optional :[line]:[col] or :[line] at the end
set -g @fingers-pattern-0 '([-a-zA-Z0-9_.~/$@]+):(\d+)(?::(\d+))?'
set -g @fingers-ctrl-action "xargs -I {} tmux run-shell 'cd #{pane_current_path}; ~/.config/tmux/plugins/tmux-open-nvim/scripts/ton {} > ~/.config/tmux/plugins/tmux-open-nvim/ton.log'"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
